-- Migration: Platzhalter - bewusst ohne Wirkung
-- Feature: features/plentyone/overview.md
--
-- Hier stand eine Tabelle, die dem Hersteller-Import feste PlentyONE-IDs
-- vorgeben sollte. Die offizielle Feldliste des Imports (07.09.2026) zeigt
-- jedoch: es gibt gar kein Zuordnungsfeld fuer die Hersteller-ID. PlentyONE
-- vergibt sie selbst, ein neuer Verlag bekommt immer die naechste freie.
--
-- Die Nummer bleibt vergeben, damit die Reihenfolge der Migrationen und die
-- bereits ausgefuehrte Zuruecknahme nachvollziehbar bleiben.
SELECT 1;
